- name: "Ensure cron daemon is enabled"
  service:
      name: cron
      enabled: true
  when:
      - ubuntu1804cis_cron_rule_1
  tags:
      - cis
      - backend
 
- name: "Ensure permissions on /etc/crontab are configured"
  file:
      dest: /etc/crontab
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_cron_rule_2
  tags:
      - cis
      - backend

- name: "Ensure permissions on /etc/cron.hourly are configured"
  file:
      dest: /etc/cron.hourly
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_cron_rule_3
  tags:
      - cis
      - backend

- name: "Ensure permissions on /etc/cron.daily are configured"
  file:
      dest: /etc/cron.daily
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_cron_rule_4
  tags:
      - cis
      - backend

- name: "Ensure permissions on /etc/cron.weekly are configured"
  file:
      dest: /etc/cron.weekly
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_cron_rule_5
  tags:
      - cis
      - backend

- name: "Ensure permissions on /etc/cron.monthly are configured"
  file:
      dest: /etc/cron.monthly
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_cron_rule_6
  tags:
      - cis
      - backend

- name: "Ensure permissions on /etc/cron.d are configured"
  file:
      dest: /etc/cron.d
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_cron_rule_7
  tags:
      - cis
      - backend

