- name: "Ensure Auditd Wrappers is installed"
  apt:
      name: auditd
      state: present
  when:
      - ubuntu1804cis_log_rule_1
  tags:
      - cis
      - backend

- name: "Ensure audit log storage size is configured"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file( |=)"
      line: "max_log_file = 600"
      state: present
  when:
      - ubuntu1804cis_log_rule_2
  notify:
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure audit logs are not automatically deleted"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file_action"
      line: "max_log_file_action = {{ max_log_file_action }}"
      state: present
  when:
      - ubuntu1804cis_log_rule_3
  notify:
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure auditd service is enabled"
  systemd:
      name: auditd
      state: started
      enabled: true
  when:
      - ubuntu1804cis_log_rule_4
  tags:
      - cis
      - backend

- name: "Ensure auditing for processes that start prior to auditd is enabled"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
      replace: '\1"\2 audit=1"'
      follow: true
  ignore_errors: true
  notify:
      - generate new grub config
  when:
      - ubuntu1804cis_log_rule_5
  tags:
      - cis
      - backend

- name: "Ensure events that modify date and time information are collected"
  template:
      src: clock.rules.j2
      dest: /etc/audit/rules.d/clock.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_6
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure events that modify user/group information are collected"
  template:
      src: upass.rules.j2
      dest: /etc/audit/rules.d/upass.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_7
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure events that modify the system's network environment are collected"
  template:
      src: netenv.rules.j2
      dest: /etc/audit/rules.d/netenv.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_8
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure events that modify the system's Mandatory Access Controls are collected"
  template:
      src: ac.rules.j2
      dest: /etc/audit/rules.d/ac.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_9
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure login and logout events are collected"
  template:
      src: login.rules.j2
      dest: /etc/audit/rules.d/login.rules.j2
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_10
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure session initiation information is collected"
  template:
      src: session.rules.j2
      dest: /etc/audit/rules.d/session.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_11
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure discretionary access control permission modification events are collected"
  template:
      src: acmod.rules.j2
      dest: /etc/audit/rules.d/acmod.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_12
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure unsuccessful unauthorized file access attempts are collected"
  template:
      src: file.rules.j2
      dest: /etc/audit/rules.d/file.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_13
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure successful file system mounts are collected"
  template:
      src: filemount.rules.j2
      dest: /etc/audit/rules.d/filemount.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_14
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure file deletion events by users are collected"
  template:
      src: del.rules.j2
      dest: /etc/audit/rules.d/del.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_15
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure changes to system administration scope (sudoers) is collected"
  template:
      src: sudo.rules.j2
      dest: /etc/audit/rules.d/sudo.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_16
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure system administrator actions (sudolog) are collected"
  template:
      src: sudolog.rules.j2
      dest: /etc/audit/rules.d/sudolog.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_17
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure kernel module loading and unloading is collected"
  template:
      src: module.rules.j2
      dest: /etc/audit/rules.d/module.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_18
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend

- name: "Ensure the audit configuration is immutable"
  template:
      src: auditconf.rules.j2
      dest: /etc/audit/rules.d/auditconf.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_log_rule_19
  notify:
      - load audit rules
      - restart auditd
  tags:
      - cis
      - backend


#### Configure Logging ##

- name: "Ensure rsyslog is installed"
  apt:
      name: rsyslog
      state: present
      install_recommends: false
  when:
      - ubuntu1804cis_log_rule_20
  tags:
      - cis
      - backend

- name: "Ensure rsyslog Service is enabled"
  systemd:
      name: rsyslog
      state: started
      enabled: yes
  when:
      - ubuntu1804cis_log_rule_21
  tags:
      - cis
      - backend

- name: "Ensure logging is configured"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu1804cis_log_rule_22
  tags:
      - cis
      - backend

- name: "Ensure rsyslog default file permissions configured"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'
  when:
      - ubuntu1804cis_log_rule_23
  tags:
      - cis
      - backend








