- name: "Ensure password creation requirements are configured"
  block:
      - name: "Ensure lipam-pwquality is installed"
        apt:
            name: libpam-pwquality
            state: present

      - name: "Ensure password creation requirements are configured"
        lineinfile:
            state: present
            dest: /etc/security/pwquality.conf
            regexp: '^{{ item.key }}'
            line: '{{ item.key }} = {{ item.value }}'
        with_items:
            - { key: 'minlen', value: '8' }
  when:
      - ubuntu1804cis_pam_rule_1
  tags:
      - cis
      - backend

- name: "Ensure lockout for failed password attempts is configured"
  lineinfile:
      state: present
      dest: /etc/pam.d/common-auth
      insertafter: EOF
      line: "auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900"
  when:
      - ubuntu1804cis_pam_rule_2
  tags:
      - cis
      - backend

- name: "Ensure the counter only gets reset when the following line is added to pam configuration"
  lineinfile:
      state: present
      dest: /etc/pam.d/common-auth
      insertafter: EOF
      line: "account required pam_tally2.so"
  when:
      - ubuntu1804cis_pam_rule_2
  tags:
      - cis
      - backend

- name: "Ensure password hashing algorithm is SHA-512"
  command: authconfig --passalgo=sha512 --update
  changed_when: false
  failed_when: false
  when:
      - ubuntu1804cis_pam_rule_3
  tags:
      - cis
      - backend


