- name: "Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
      dest: /etc/ssh/sshd_config
      state: file
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_ssh_rule_1
  tags:
      - cis
      - backend

- name: "Ensure SSH Protocol is set to 2"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Protocol'
      line: 'Protocol 2'
  when:
      - ubuntu1804cis_ssh_rule_2
  tags:
      - cis
      - backend

- name: "Ensure SSH LogLevel is set to INFO"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^LogLevel'
      line: 'LogLevel INFO'
  when:
      - ubuntu1804cis_ssh_rule_3
  tags:
      - cis
      - backend

- name: "Ensure SSH X11 forwarding is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^X11Forwarding'
      line: 'X11Forwarding no'
  when:
      - ubuntu1804cis_ssh_rule_4
  tags:
      - cis
      - backend

- name: "Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?MaxAuthTries \d'
      line: 'MaxAuthTries 4'
  when:
      - ubuntu1804cis_ssh_rule_5
  tags:
      - cis
      - backend

- name: "Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^IgnoreRhosts'
      line: 'IgnoreRhosts yes'
  when:
      - ubuntu1804cis_ssh_rule_6
  tags:
      - cis
      - backend

- name: "Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^HostbasedAuthentication'
      line: 'HostbasedAuthentication no'
  when:
      - ubuntu1804cis_ssh_rule_7
  tags:
      - cis
      - backend

- name: "Ensure SSH root login is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
  when:
      - ubuntu1804cis_ssh_rule_8
  tags:
      - cis
      - backend

- name: "Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
  when:
      - ubuntu1804cis_ssh_rule_9
  tags:
      - cis
      - backend

- name: "Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitUserEnvironment'
      line: 'PermitUserEnvironment no'
  when:
      - ubuntu1804cis_ssh_rule_10
  tags:
      - cis
      - backend

- name: "Ensure only approved MAC algorithms are used"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^MACs'
      line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
  when:
      - ubuntu1804cis_ssh_rule_11
  tags:
      - cis
      - backend

- name: "Ensure SSH Idle Timeout Interval is configured"
  block:
      - name: "Ensure SSH Idle Timeout Interval is configured"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^ClientAliveInterval'
            line: "ClientAliveInterval {{ ubuntu1804cis_sshd['clientaliveinterval'] }}"

      - name: "Ensure SSH ClientAliveCountMax set to <= 3"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^ClientAliveCountMax'
            line: "ClientAliveCountMax {{ ubuntu1804cis_sshd['clientalivecountmax'] }}"
  when:
      - ubuntu1804cis_ssh_rule_12
  tags:
      - cis
      - backend

- name: "Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^LoginGraceTime'
      line: "LoginGraceTime 60"
  when:
      - ubuntu1804cis_ssh_rule_13
  tags:
      - cis
      - backend

- name: "Ensure SSH access is limited"
  block:
      - name: "Ensure SSH access is limited - allowusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^AllowUsers'
            line: "AllowUsers {{ ubuntu1804cis_sshd['allowusers'] }}"
        notify:
            - restart sshd
        when:
            - "ubuntu1804cis_sshd['allowusers']|default('') != ''"

      - name: "Ensure SSH access is limited - allowgroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^AllowGroups'
            line: "AllowGroups {{ ubuntu1804cis_sshd['allowgroups'] }}"
        notify:
            - restart sshd
        when:
            - "ubuntu1804cis_sshd['allowgroups']|default('') != ''"

      - name: "Ensure SSH access is limited - denyusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^DenyUsers'
            line: "DenyUsers {{ ubuntu1804cis_sshd['denyusers'] }}"
        notify:
            - restart sshd
        when:
            - "ubuntu1804cis_sshd['denyusers']|default('') != ''"

      - name: "Ensure SSH access is limited - denygroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^DenyGroups'
            line: "DenyGroups {{ ubuntu1804cis_sshd['denygroups'] }}"
        notify:
            - restart sshd
        when:
            - "ubuntu1804cis_sshd['denygroups']|default('') != ''"
  when:
      - ubuntu1804cis_ssh_rule_14
  tags:
      - cis
      - backend

- name: "Ensure SSH warning banner is configured"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Banner'
      line: 'Banner /etc/issue.net'
  when:
      - ubuntu1804cis_ssh_rule_15
  tags:
      - cis
      - backend

- name: "Ensure auto logout after 10 mins"
  lineinfile:
      state: present
      dest: /etc/bash.bashrc
      insertafter: EOF
      line: "TMOUT=600"
  when:
      - ubuntu1804cis_ssh_rule_16
  tags:
      - cis
      - backend
                                               189,0-1       65%
