---
# handlers file for CIS-Ubuntu-Hardnening-18-04

- name: sysctl flush ipv4 route table
  become: true
  sysctl:
      name: net.ipv4.route.flush
      value: 1
      sysctl_set: true

- name: sysctl flush ipv6 route table
  become: true
  sysctl:
      name: net.ipv6.route.flush
      value: 1
      sysctl_set: true

- name: restart auditd
  become: true
  service:
      name: auditd
  state: restarted

- name: generate new grub config
  become: true
  command: grub-mkconfig -o "{{ grub_cfg.stat.path }}"

- name: load audit rules
  become: true
  command: /sbin/augenrules --load


